version: 0.0
<<<<<<< HEAD
os: linux
files:
  - source: /scripts
    destination: /var/www/html/scripts
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/afterinstall
      runas: root

=======
files:
	- source: /root/
	  destination: /var/www/html/
>>>>>>> 79d4bcc6e664d191fe0c795d8a73d8a89d1a28f4
