<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

Configure::write('recharge_apis',array(
                    '8'=>array('name'=>'cp','txn_id'=>'6','vendor_ref_id'=>'7','status'=>'8','amount'=>'5','type'=>'0','api_status'=>array('pending'=>'0','success'=>'1','failed'=>'2'))
                    ,'24'=>array('name'=>'magic','txn_id'=>'9','vendor_ref_id'=>'8','status'=>'7','amount'=>'6','type'=>'0','api_status'=>array('pending'=>'0','success'=>'1','failure'=>'2'))
                    ,'57'=>array('name'=>'mypay','txn_id'=>'14','vendor_ref_id'=>'13','status'=>'11','amount'=>'3','type'=>'0','api_status'=>array(''=>'0','success'=>'1','fail'=>'2'))
                    ,'58'=>array('name'=>'smsdaak','txn_id'=>'2','vendor_ref_id'=>'1','status'=>'13','amount'=>'11','type'=>'0','api_status'=>array('pending'=>'0','success'=>'1','refund'=>'2'))
                    ,'63'=>array('name'=>'aporec','txn_id'=>'1','vendor_ref_id'=>'0','status'=>'3','amount'=>'2','type'=>'0','api_status'=>array(''=>'0','success'=>'1','failed'=>'2'))
                    ,'65'=>array('name'=>'hitech','txn_id'=>'1','vendor_ref_id'=>'21','status'=>'12','amount'=>'7','type'=>'0','api_status'=>array('request send'=>'0','success'=>'1','failed'=>'2','manual failed'=>'2'))
                    ,'68'=>array('name'=>'practic','txn_id'=>'5','vendor_ref_id'=>'','status'=>'4','amount'=>'3','type'=>'2','api_status'=>array('process'=>'0','suspense'=>'0','success'=>'1','failure'=>'2',' refund'=>'2'))
                    ,'87'=>array('name'=>'manglam','txn_id'=>'4','vendor_ref_id'=>'3','status'=>'12','amount'=>'10','type'=>'0','api_status'=>array(''=>'0','success'=>'1','failure'=>'2'))
                    ,'105'=>array('name'=>'bulk','txn_id'=>'1','vendor_ref_id'=>'0','status'=>'6','amount'=>'4','type'=>'0','api_status'=>array(''=>'0','success'=>'1','failure'=>'2'))
                    ,'134'=>array('name'=>'indiCore','txn_id'=>'2','vendor_ref_id'=>'3','status'=>'10','amount'=>'7','type'=>'0','api_status'=>array(''=>'0','success'=>'1','successfull'=>'1','failed'=>'2'))
                    ,'135'=>array('name'=>'swamiraj','txn_id'=>'1','vendor_ref_id'=>'0','status'=>'5','amount'=>'3','type'=>'0','api_status'=>array(''=>'0','success'=>'1','failed'=>'2','revert'=>'2'))
//                    ,'144'=>array('name'=>'','txn_id'=>'','vendor_ref_id'=>'','status'=>'','amount'=>'','type'=>'0','api_status'=>array(''=>'0',''=>'1',''=>'2'))
                    ,'149'=>array('name'=>'ambika','txn_id'=>'10','vendor_ref_id'=>'1','status'=>'6','amount'=>'5','type'=>'2','api_status'=>array(''=>'0','success'=>'1','failed'=>'2','refund'=>'2'))
                    ,'150'=>array('name'=>'a1rec','txn_id'=>'2','vendor_ref_id'=>'','status'=>'8','amount'=>'5','type'=>'2','api_status'=>array('pending'=>'0','success'=>'1','refund'=>'2'))
                    ,'151'=>array('name'=>'unrec','txn_id'=>'10','vendor_ref_id'=>'0','status'=>'8','amount'=>'4','type'=>'0','api_status'=>array(''=>'0','success'=>'1','failure'=>'2','refunded'=>'2'))
                    ,'152'=>array('name'=>'speedrec','txn_id'=>'','vendor_ref_id'=>'9','status'=>'13','amount'=>'5','type'=>'1','api_status'=>array(''=>'0','success'=>'1','fail'=>'2'))
                    ,'155'=>array('name'=>'ambikaroam','txn_id'=>'10','vendor_ref_id'=>'1','status'=>'6','amount'=>'5','type'=>'2','api_status'=>array(''=>'0','success'=>'1','failed'=>'2','refund'=>'2'))
                    ,'156'=>array('name'=>'bigshoprec','txn_id'=>'6','vendor_ref_id'=>'7','status'=>'12','amount'=>'9','type'=>'0','api_status'=>array(''=>'0','success'=>'1','failure'=>'2'))
                    ,'157'=>array('name'=>'indiaone','txn_id'=>'9','vendor_ref_id'=>'0','status'=>'8','amount'=>'3','type'=>'0','api_status'=>array(''=>'0','success'=>'1','failure'=>'2','refund'=>'2','reversal'=>'2','recharge'=>'1','recharge - reversal'=>'2'))
                    ,'160'=>array('name'=>'speedpay','txn_id'=>'18','vendor_ref_id'=>'1','status'=>'20','amount'=>'8','type'=>'0','api_status'=>array(''=>'0','success'=>'1','fail'=>'2'))
                    ,'161'=>array('name'=>'cca','txn_id'=>'','vendor_ref_id'=>'0','status'=>'6','amount'=>'2','type'=>'1','api_status'=>array(''=>'0','successful'=>'1','failure'=>'2','reversals'=>'2','unsuccessful'=>'2'))
                    ,'162'=>array('name'=>'thinkwal','txn_id'=>'6','vendor_ref_id'=>'5','status'=>'1','amount'=>'2','type'=>'0','api_status'=>array(''=>'0','success'=>'1','failed'=>'2','rollback'=>'2'))
                    ,'163'=>array('name'=>'champrec','txn_id'=>'2','vendor_ref_id'=>'1','status'=>'11','amount'=>'9','type'=>'0','api_status'=>array(''=>'0','success'=>'1','failure'=>'2'))
                    ,'164'=>array('name'=>'yashicaent','txn_id'=>'13','vendor_ref_id'=>'11','status'=>'12','amount'=>'7','type'=>'0','api_status'=>array(''=>'0','success'=>'1','failed'=>'2','refunded'=>'2'))
                    ,'165'=>array('name'=>'ka2zrec','txn_id'=>'18','vendor_ref_id'=>'1','status'=>'20','amount'=>'8','type'=>'0','api_status'=>array(''=>'0','success'=>'1','fail'=>'2'))
                    ,'166'=>array('name'=>'roundpay','txn_id'=>'9','vendor_ref_id'=>'1','status'=>'10','amount'=>'6','type'=>'0','api_status'=>array('pending'=>'0','success'=>'1','failed'=>'2','refund'=>'2'))
                    ,'167'=>array('name'=>'maxxrec','txn_id'=>'2','vendor_ref_id'=>'','status'=>'8','amount'=>'5','type'=>'2','api_status'=>array('pending'=>'0','success'=>'1','failed'=>'2','refund'=>'2'))
                    ,'168'=>array('name'=>'erecpoint','txn_id'=>'2','vendor_ref_id'=>'','status'=>'10','amount'=>'5','type'=>'2','api_status'=>array('pending'=>'0','success'=>'1','failed'=>'2','refund'=>'2'))
                    ,'169'=>array('name'=>'urec','txn_id'=>'','vendor_ref_id'=>'1','status'=>'5','amount'=>'6','type'=>'1','api_status'=>array(''=>'0','success'=>'1','failure'=>'2','refund'=>'2'))
                    ,'170'=>array('name'=>'pay1all','txn_id'=>'8','vendor_ref_id'=>'0','status'=>'10','amount'=>'5','type'=>'0','api_status'=>array('pending'=>'0','success'=>'1','failed'=>'2','refund'=>'2'))
                    ,'171'=>array('name'=>'prec','txn_id'=>'8','vendor_ref_id'=>'0','status'=>'7','amount'=>'3','type'=>'0','api_status'=>array('pending'=>'0','success'=>'1','failure'=>'2','reversal'=>'2'))
                    ,'172'=>array('name'=>'ashw1','txn_id'=>'','vendor_ref_id'=>'','status'=>'','amount'=>'','type'=>'0','api_status'=>array('pending'=>'0','success'=>'1','failure'=>'2','reversal'=>'2'))
                    ,'173'=>array('name'=>'pay1click','txn_id'=>'10','vendor_ref_id'=>'0','status'=>'6','amount'=>'3','type'=>'0','api_status'=>array('pending'=>'0','success'=>'1','failure'=>'2','rollback'=>'2'))
                    ,'174'=>array('name'=>'kracrec','txn_id'=>'18','vendor_ref_id'=>'1','status'=>'20','amount'=>'8','type'=>'0','api_status'=>array('pending'=>'0','success'=>'1','fail'=>'2'))
                    ,'175'=>array('name'=>'stelcom','txn_id'=>'','vendor_ref_id'=>'','status'=>'','amount'=>'','type'=>'0','api_status'=>array('pending'=>'0','success'=>'1','fail'=>'2'))
                    ,'176'=>array('name'=>'manimaster','txn_id'=>'2','vendor_ref_id'=>'1','status'=>'5','amount'=>'7','type'=>'0','api_status'=>array('pending'=>'0','success'=>'1','failure'=>'2','reversed'=>'2'))
                    ,'177'=>array('name'=>'wellborn','txn_id'=>'4','vendor_ref_id'=>'3','status'=>'10','amount'=>'8','type'=>'0','api_status'=>array('pending'=>'0','success'=>'1','failure'=>'2'))
                    ,'180'=>array('name'=>'myetopup','txn_id'=>'2','vendor_ref_id'=>'','status'=>'10','amount'=>'5','type'=>'2','api_status'=>array('pending'=>'0','success'=>'1','refund'=>'2'))
                    ,'184'=>array('name'=>'manglamvod','txn_id'=>'4','vendor_ref_id'=>'3','status'=>'12','amount'=>'10','type'=>'0','api_status'=>array('pending'=>'0','success'=>'1','failure'=>'2'))
                    ,'185'=>array('name'=>'swamirapi','txn_id'=>'','vendor_ref_id'=>'10','status'=>'14','amount'=>'6','type'=>'1','api_status'=>array('pending'=>'0','success'=>'1','fail'=>'2'))
                    ,'189'=>array('name'=>'varsharobo','txn_id'=>'','vendor_ref_id'=>'0','status'=>'8','amount'=>'10','type'=>'1','api_status'=>array('pending'=>'0','success'=>'1','failed'=>'2'))
                    ,'190'=>array('name'=>'qubarobo','txn_id'=>'','vendor_ref_id'=>'0','status'=>'8','amount'=>'10','type'=>'1','api_status'=>array('pending'=>'0','success'=>'1','failed'=>'2'))
                    ,'191'=>array('name'=>'handloome','txn_id'=>'','vendor_ref_id'=>'0','status'=>'8','amount'=>'10','type'=>'1','api_status'=>array('pending'=>'0','success'=>'1','failed'=>'2'))
                    ,'192'=>array('name'=>'threeplus','txn_id'=>'','vendor_ref_id'=>'0','status'=>'8','amount'=>'10','type'=>'1','api_status'=>array('pending'=>'0','success'=>'1','failed'=>'2'))
                    ,'193'=>array('name'=>'pintoosls','txn_id'=>'','vendor_ref_id'=>'0','status'=>'8','amount'=>'10','type'=>'1','api_status'=>array('pending'=>'0','success'=>'1','failed'=>'2'))
                    ,'194'=>array('name'=>'aventerp','txn_id'=>'','vendor_ref_id'=>'0','status'=>'8','amount'=>'10','type'=>'1','api_status'=>array('pending'=>'0','success'=>'1','failed'=>'2'))
                    ,'195'=>array('name'=>'jasscomm','txn_id'=>'','vendor_ref_id'=>'0','status'=>'8','amount'=>'10','type'=>'1','api_status'=>array('pending'=>'0','success'=>'1','failed'=>'2'))
                    ,'196'=>array('name'=>'nkagency','txn_id'=>'','vendor_ref_id'=>'0','status'=>'8','amount'=>'10','type'=>'1','api_status'=>array('pending'=>'0','success'=>'1','failed'=>'2'))
                    ,'197'=>array('name'=>'anilkir','txn_id'=>'','vendor_ref_id'=>'0','status'=>'8','amount'=>'10','type'=>'1','api_status'=>array('pending'=>'0','success'=>'1','failed'=>'2'))
                    ,'198'=>array('name'=>'jeevnrkh','txn_id'=>'','vendor_ref_id'=>'0','status'=>'8','amount'=>'10','type'=>'1','api_status'=>array('pending'=>'0','success'=>'1','failed'=>'2'))
            )
        );